a = int(input("Que valor de a deseas: "))
b = int(input("Que valor de b deseas: "))
def math(a, b):
    print(a + b)
    print(a - b)
    print(a * b)
    print((a + b)/2)
    print(int(a / b))
    print(a % b)
    print(a / b)
def math(a, b) 
